# This is a basic workflow to help you get started with Actions

name: Build Jekyll

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  jekyll:
    name: Build and deploy Jekyll site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v2

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Build
      uses: jerryjvl/jekyll-build-action@v1
           
    - name: Deploy to storage
      uses: bacongobbler/azure-blob-storage-upload@v1.1.1
      with:
        source_dir: '_site'
        container_name: '$web'
        connection_string: ${{ secrets.CONNECTION_STRING }}
        sync: true